### ISSUE TITLE
while save ~/.bashrc after find wrong

### ISSUE THREAD

**Issue by 1225358814** [utahta/pythonbrew#151]
this@this-this:~$ source ~/.bashrc 
An error has occurred: init.run: /path/to/.pythonbrew/cache: mkdir /path: permission denied
未找到 'See' 命令，您要输入的是否是：
 命令 'pee' 来自于包 'moreutils' (universe)
 命令 'ree' 来自于包 'ree' (universe)
 命令 'see' 来自于包 'mime-support' (main)
 命令 'tee' 来自于包 'coreutils' (main)
See：未找到命令
this@this-this:~$ pythonbrew init
An error has occurred: init.run: /path/to/.pythonbrew/cache: mkdir /path: permission denied
See more details: /tmp/pythonbrew056139890/pythonbrew.log

**Comment by utahta** [comment]
`/path/to` is just an example.
You should set a path to writable directory.
